In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
v_neuron = np.array([-65, -70])
A = csr_matrix(np.matrix([1, 1]))
y = -65

In [3]:
print(A)

  (0, 0)	1
  (0, 1)	1


In [4]:


np.sum(np.subtract(y, v_neuron))

5

In [5]:
np.sum(A * (np.subtract(y,v_neuron)))

5

In [6]:
(A.multiply(np.subtract.outer(v_neuron[0],v_neuron[0]))).sum(axis=0)

matrix([[0, 0]])

In [7]:
from utils.connectivity import *

In [8]:
E_matrix, seed = create_matrix('pair')

In [9]:
from scipy import sparse

In [10]:
E_matrix = sparse.csr_matrix(E_matrix)

In [11]:
import numpy as np

In [12]:
y = np.array([-70,-70])
y_2 = np.array([-10.0008,-500.0008])

In [13]:
np.ravel((E_matrix.multiply(np.subtract.outer(y, y))).sum(axis=0))

array([0, 0])

In [19]:
np.subtract.outer(y_2, y_2)

array([[   0.,  490.],
       [-490.,    0.]])

In [14]:
np.ravel((E_matrix.multiply(np.subtract.outer(y_2, y_2))).sum(axis=0))

array([-490.,  490.])

In [15]:
print(type((E_matrix.multiply(np.subtract.outer(y_2, y_2)))))

<class 'scipy.sparse._coo.coo_matrix'>


In [16]:
print(y_2)

[ -10.0008 -500.0008]


In [17]:
print(np.shape((y_2)))

(2,)
